### ISSUE TITLE
Failed to load after adding items

### ISSUE THREAD

**Issue by ichbinashh** [jakubvanko/minecraft-plugins#2]
Hey, so I've tried to add a load of vanilla items into the config and after doing so it fails to load the plugin. Obviously I've done something wrong, but I don't see where. YAML Parsers tell me it's all okay so I was hoping you could help me out.

The error is https://pastebin.com/XEyFTPUV
My config https://pastebin.com/vtHCHV7u

I started by adding all of the items and material, then I was slowly adding them to the reward tiers but I figured I should stop and check before I got too far.

Any help is much appreciated :)

**Comment by jakubvanko** [comment]
Hello.
Firstly, let me sincerely apologize for such a late answer. You were the first person to ever create an issue on Github regading my Minecraft plugins and therefore I have overlooked it.
The main problem with your config was that there is no such enchantment in Bukkit called **FORTUNE**. The correct name for it is **LOOT_BONUS_BLOCKS**. Otherwise, your config was correct.
